#!/bin/env bash


source "helpers/sitegen"


if [[ $1 == "-devel" ]];then
    packer_webdev
fi

if [[ $1 == "-builds" ]];then
    packer_webpub    
fi

if [[ $1 == "-apigen" ]];then
    packer_apigen
fi

if [[ $1 == "-wikigen" ]];then
    packer_wikigen
fi